// actionType.js
export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';



export const FETCH_WEEKLY_WEATHER_REQUEST = 'FETCH_WEEKLY_WEATHER_REQUEST';
export const FETCH_WEEKLY_WEATHER_SUCCESS = 'FETCH_WEEKLY_WEATHER_SUCCESS';
export const FETCH_WEEKLY_WEATHER_FAILURE = 'FETCH_WEEKLY_WEATHER_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
