// actionType.js
export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const FETCH_WEEKLY_WEATHER_REQUEST = 'FETCH_WEEKLY_WEATHER_REQUEST';
export const FETCH_WEEKLY_WEATHER_SUCCESS = 'FETCH_WEEKLY_WEATHER_SUCCESS';
export const FETCH_WEEKLY_WEATHER_FAILURE = 'FETCH_WEEKLY_WEATHER_FAILURE';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY';

export const ADD_CITY_WEATHER_TO_FAVORITES = 'ADD_CITY_WEATHER_TO_FAVORITES';

export const FETCH_HOURLY_WEATHER_REQUEST = 'FETCH_HOURLY_WEATHER_REQUEST';
export const FETCH_HOURLY_WEATHER_SUCCESS = 'FETCH_HOURLY_WEATHER_SUCCESS';
export const FETCH_HOURLY_WEATHER_FAILURE = 'FETCH_HOURLY_WEATHER_FAILURE';
